complete -c dualsensectl -s l -l list -d 'Print connected devices'
complete -c dualsensectl -s d -l device -d 'Specify which device to use'
complete -c dualsensectl -s w -l wait -d 'Waiting Monitor shell command for events'
complete -c dualsensectl -s h -l help -d 'Print help text'
complete -c dualsensectl -s v -l version -d 'Print version number'
complete -c dualsensectl -a 'power-off' -d 'Turn off the controller (Bluetooth only)'
complete -c dualsensectl -a 'battery' -d 'Get the controller battery level and charging/discharging information'
complete -c dualsensectl -a 'info' -d 'Get the controller firmware information'
complete -c dualsensectl -a 'lightbar' -d 'Set lightbar color and brightness [RED] [GREEN] [BLUE] [BRIGHTNESS] - [0-255] [0-255] [0-255] [0-255]'
complete -c dualsensectl -a 'player-leds' -d 'Set player LEDs [1-5] or disabled [0]'
complete -c dualsensectl -a 'microphone' -d 'Enable [ON] or disable [OFF] microphone'
complete -c dualsensectl -a 'microphone-led' -d 'Enable [ON] or disable [OFF] microphone orange LED'
complete -c dualsensectl -a 'speaker' -d 'Toggle to [INTERNAL] speaker, [HEADPHONE], [MONOHEADPHONE] or [BOTH] outputs'
complete -c dualsensectl -a 'volume' -d 'Set audio volume [0-255] of internal speaker and headphone'
complete -c dualsensectl -a 'attenuation' -d 'Set the attenuation [0-7] [0-7] of rumble/haptic motors and trigger vibration'
complete -c dualsensectl -a 'trigger' -d 'Set the trigger [LEFT], [RIGHT] or [BOTH] mode with parameters (up to 9)'
complete -c dualsensectl -a 'monitor' -d 'Run Monitor shell [add/remove `command`] on add/remove events'
